# Generated by Django 6.0 on 2025-12-20 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
