# Generated by Django 6.0 on 2025-12-21 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_medium_subscriptionservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='mediums',
            field=models.ManyToManyField(blank=True, to='tracker.medium'),
        ),
        migrations.AddField(
            model_name='library',
            name='subscription_services',
            field=models.ManyToManyField(blank=True, to='tracker.subscriptionservice'),
        ),
    ]
