# Generated by Django 6.0 on 2025-12-23 22:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_library_mediums_library_subscription_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='priority',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
